name = "Example"
uuid = "64871c92-8883-47dd-bc64-a32b69a9ff01"
authors = ["gregorykimmel <gregory.kimmel89@gmail.com>"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
